# Generated by Django 5.0.4 on 2024-04-11 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_book_options_remove_book_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='author name')),
                ('birth_date', models.DateField(verbose_name='birth date')),
                ('birth_place', models.CharField(max_length=100, verbose_name='birth place')),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='death date')),
                ('death_place', models.CharField(blank=True, max_length=100, null=True, verbose_name='death place')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'author',
                'verbose_name_plural': 'authors',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='market.author', verbose_name='author'),
        ),
    ]
