# Generated by Django 5.0.4 on 2024-04-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_author_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='portrait',
            field=models.ImageField(blank=True, upload_to='portraits/', verbose_name='author portrait'),
        ),
    ]
