# Generated by Django 5.0.4 on 2024-04-16 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_book_cover_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='publisher name')),
                ('founded_year', models.IntegerField(verbose_name='founded year')),
                ('country', models.CharField(max_length=100, verbose_name='country')),
                ('website', models.URLField(blank=True, null=True, verbose_name='website')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='email')),
            ],
            options={
                'verbose_name': 'publisher',
                'verbose_name_plural': 'publishers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BookPublisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_date', models.DateField(verbose_name='publication date')),
                ('edition', models.CharField(blank=True, max_length=100, null=True, verbose_name='edition')),
                ('published_copies', models.IntegerField(blank=True, null=True, verbose_name='published copies')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.book', verbose_name='book')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.publisher', verbose_name='publisher')),
            ],
            options={
                'verbose_name': 'book publisher',
                'verbose_name_plural': 'book publishers',
            },
        ),
    ]
